name: ZeeShaikh
favicon: null
layout_spectrum: 0.6751369922421873
typography_spectrum: 0.776812851196155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.06449299631640315
  lightness: 0.8537957377266139
  saturation: 0.8565455230418593
  rhythmicContrast: 0.5945639181882143
purpose: []
